#pylint: disable=all
import pyfbsdk
from typing import Any, Callable

def GetFBEventSource(source, eventtype) -> Any:
    ...
def RemoveAllEvents(source):
    ...
def GetEventSource(source, eventtype) -> Any:
    ...
def NotifyEventSource(source, event):
    ...
class EventSource(object):
    control: pyfbsdk.FBPlug
    eventtype: pyfbsdk.FBEventName
    callbacks: list[pyfbsdk.FBCallback]
    
    def __init__(self, control, eventtype):
        ...
    def Add(self, toCall: Callable):
        ...
    def Remove(self, toRemove: Callable):
        ...
    def RemoveAll(self):
        ...
    def Notify(self, event):
        ...
class FBEventSource(EventSource):
    def __init__(self, control, eventtype):
        ...
    def Add(self, toCall):
        ...
    def Remove(self, toRemove):
        ...